=== SrMilla/Sistema-Multiagentes-2021-esiiab/Equipo 2/MensajeError.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Error">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Info" type="infoMensaje"/>
                <xs:element name="ID" type="Codigo"/>
                <xs:element name="MensajeError" type="MError"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="Codigo">
        <xs:restriction base="xs:integer">
            <!--0 - Error no definido -->
            <!--1 - Faltan Datos -->
            <!--2 - Datos Erroneos -->
            <!--3 - Error de conexion -->
            <!--4 - Problema en la operacion -->
            <!--5 - Cabecera Erronea -->
            <xs:pattern value="[0-5]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="MError">
        <xs:sequence>
            <xs:element name="Texto">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <!--<xs:pattern value="[a-zA-Z0-9 ]"/>-->
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="MensajeProv" type="infoMensaje"/>
        </xs:sequence>
    </xs:complexType>



    <!--InfoMensaje Grupo 4-->
    <xs:complexType name="infoMensaje">
        <xs:sequence> 
            <xs:element name="emisor" type="IdAgente"/> 
            <xs:element name="receptor" type="IdAgente"/> 
            <xs:element name="id" type="ID"/> 
            <xs:element name="protocolo" type="Protocolo"/> 
            <xs:element name="tipo" type="TipoMensaje"/> 
        </xs:sequence> 
    </xs:complexType>


    <xs:simpleType name="Protocolo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="alta"/>
            <xs:enumeration value="inicio_actividad"/>
            <xs:enumeration value="entrada_tienda"/>
            <xs:enumeration value="compra"/>
            <xs:enumeration value="solicitar_tiendas"/>
            <xs:enumeration value="salida_tienda"/>
            <xs:enumeration value="ACK"/>
            <xs:enumeration value="finalizacion"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoMensaje">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MSI"/>
            <xs:enumeration value="MCI"/>
            <xs:enumeration value="MEI"/>
            <xs:enumeration value="MAE"/>
            <xs:enumeration value="MSET"/>
            <xs:enumeration value="MSIP"/>
            <xs:enumeration value="MIP"/>
            <xs:enumeration value="MCP"/>
            <xs:enumeration value="MVP"/>
            <xs:enumeration value="MSIT"/>
            <xs:enumeration value="MIT"/>
            <xs:enumeration value="MSST"/>
            <xs:enumeration value="MFO"/>
            <xs:enumeration value="ACK"/>
            <xs:enumeration value="MError"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="tipoIP">
        <xs:restriction base="xs:string">
			<xs:pattern value="([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="ID">
        <xs:sequence>
            <xs:element name="ipemisor" type="tipoIP"/>
            <xs:element name="contador" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="IdAgente">
        <xs:sequence>
            <xs:element name="IP" type="tipoIP"/>
            <xs:element name="ID" type="xs:integer"/>
            <xs:element name="tipo" type="tipoAgente"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tipoAgente">
        <xs:restriction base="xs:string">
            <xs:enumeration value="monitor"/>
            <xs:enumeration value="comprador"/>
            <xs:enumeration value="tienda"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== SrMilla/Sistema-Multiagentes-2021-esiiab/Equipo 2/MensajeErrorEjemplo.xml
<?xml version="1.0"?>
<Error xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MensajeError.xsd">
    <Info>
        <emisor>
            <IP>192.168.0.1</IP>
            <ID>1</ID>
            <tipo>tienda</tipo>
        </emisor>
        <receptor>
            <IP>192.168.0.2</IP>
            <ID>1</ID>
            <tipo>comprador</tipo>
        </receptor>
        <id>
            <ipemisor>192.168.0.2</ipemisor>
            <contador>2</contador>
        </id>
        <protocolo>compra</protocolo>
        <tipo>MError</tipo>
    </Info>
    <ID>1</ID>
    <MensajeError>
        <Texto>Faltan datos en el mensaje</Texto>
        <MensajeProv>
            <emisor>
                <IP>192.168.0.2</IP>
                <ID>1</ID>
                <tipo>comprador</tipo>
            </emisor>
            <receptor>
                <IP>192.168.0.1</IP>
                <ID>1</ID>
                <tipo>tienda</tipo>
            </receptor>
            <id>
                <ipemisor>192.168.0.2</ipemisor>
                <contador>1</contador>
            </id>
            <protocolo>compra</protocolo>
            <tipo>MCP</tipo>
        </MensajeProv>    
    </MensajeError>
</Error>
