=== SrMilla/Sistema-Multiagentes-2021-esiiab/Equipo 6/XML_Compra/Mensajes_Compra/MVP_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mensaje_venta_productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="info_mensaje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="emisor" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo_emisor" type="xs:string" />
                                        <xs:element name="id_emisor" type="xs:integer" />
                                        <xs:element name="ip_emisor">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="puerto_emisor" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="receptor" maxOccurs="2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo_receptor" type="xs:string" />
                                        <xs:element name="id_receptor" type="xs:integer" />
                                        <xs:element name="ip_receptor">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="puerto_receptor" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datos_mensaje" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id_mensaje" type="xs:integer" />
                                        <xs:element name="cuerpo" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="tipo_mensaje" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="MVP" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lista_productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre_producto" type="xs:string" />
                                        <xs:element name="id_producto" type="xs:integer" />
                                        <xs:element name="cantidad" type="xs:integer" />
                                        <xs:element name="precio">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:fractionDigits value="2" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SrMilla/Sistema-Multiagentes-2021-esiiab/Equipo 6/XML_Compra/Mensajes_Compra/MVP.xml
<?xml version="1.0" encoding="UTF-8"?>
<mensaje_venta_productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MVP_Schema.xsd">
    <info_mensaje>
        <emisor>
            <tipo_emisor>Tienda</tipo_emisor>
            <id_emisor>1</id_emisor>
            <ip_emisor>192.168.0.4</ip_emisor>
            <puerto_emisor>8000</puerto_emisor>
        </emisor>
        <receptor>
            <tipo_receptor>Comprador</tipo_receptor>
            <id_receptor>1</id_receptor>
            <ip_receptor>192.168.0.3</ip_receptor>
            <puerto_receptor>8000</puerto_receptor>
        </receptor>
        <receptor>
            <tipo_receptor>Monitor</tipo_receptor>
            <id_receptor>1</id_receptor>
            <ip_receptor>192.168.0.5</ip_receptor>
            <puerto_receptor>8000</puerto_receptor>
        </receptor>
        <datos_mensaje>
            <id_mensaje>3</id_mensaje>
            <cuerpo>La tienda vende los productos al comprador y lo notifica al monitor</cuerpo>
        </datos_mensaje>
        <tipo_mensaje>MVP</tipo_mensaje>
    </info_mensaje>
    <lista_productos>
        <producto>
            <nombre_producto>Aceite</nombre_producto>
            <id_producto>1</id_producto>
            <cantidad>3</cantidad>
            <precio>8.99</precio>
        </producto>
        <producto>
            <nombre_producto>Vino</nombre_producto>
            <id_producto>2</id_producto>
            <cantidad>1</cantidad>
            <precio>10.99</precio>
        </producto>
        <producto>
            <nombre_producto>Pan</nombre_producto>
            <id_producto>3</id_producto>
            <cantidad>5</cantidad>
            <precio>2.99</precio>
        </producto>
    </lista_productos>
</mensaje_venta_productos>
